"use client";

import * as React from "react";
import { CalculatorLayout, CalculatorInput, CalculatorChart, ResultCard } from "..";
import { formatCurrency, formatPercentage } from "@/lib/utils";

export default function GrossMarginCalculator() {
  const [revenue, setRevenue] = React.useState(1000000);
  const [cogs, setCogs] = React.useState(600000);

  const safeRevenue = isFinite(revenue) ? Math.max(0, revenue) : 0;
  const safeCogs = isFinite(cogs) ? Math.max(0, cogs) : 0;

  const grossProfit = safeRevenue - safeCogs;
  const grossMargin = safeRevenue > 0 ? (grossProfit / safeRevenue) * 100 : 0;

  const chartData = [
    { name: "Cost of Goods Sold", value: safeCogs },
    { name: "Gross Profit", value: grossProfit },
  ];

  return (
    <CalculatorLayout
      title="Gross Margin Calculator"
      description="Calculate gross profit and gross margin percentage from revenue and cost of goods sold."
      icon={<span>📊</span>}
      results={
        <div className="space-y-4">
          <ResultCard label="Gross Profit" value={formatCurrency(grossProfit)} highlight />
          <ResultCard label="Gross Margin" value={formatPercentage(grossMargin)} subtext="% of revenue" />
          <ResultCard label="Revenue" value={formatCurrency(safeRevenue)} subtext="Total sales" />
          <ResultCard label="COGS" value={formatCurrency(safeCogs)} subtext="Cost of goods sold" />
        </div>
      }
    >
      <CalculatorChart type="pie" data={chartData} xKey="name" yKey="value" title="Revenue Breakdown" />
      <CalculatorInput input={{ id: "revenue", label: "Revenue", type: "number", defaultValue: 1000000, suffix: "$", min: 0, step: 1000, tooltip: "Total sales revenue generated by the business." }} value={revenue} onChange={setRevenue} />
      <CalculatorInput input={{ id: "cogs", label: "Cost of Goods Sold (COGS)", type: "number", defaultValue: 600000, suffix: "$", min: 0, step: 1000, tooltip: "Direct costs attributable to the production of goods sold." }} value={cogs} onChange={setCogs} />
    </CalculatorLayout>
  );
}
