"use client";

import * as React from "react";
import { CalculatorLayout, CalculatorInput, CalculatorChart, ResultCard } from "..";
import { formatCurrency, formatPercentage } from "@/lib/utils";

export default function NetProfitMarginCalculator() {
  const [revenue, setRevenue] = React.useState(1000000);
  const [cogs, setCogs] = React.useState(600000);
  const [opEx, setOpEx] = React.useState(200000);
  const [interest, setInterest] = React.useState(30000);
  const [taxes, setTaxes] = React.useState(40000);

  const safeRevenue = isFinite(revenue) ? Math.max(0, revenue) : 0;
  const safeCogs = isFinite(cogs) ? Math.max(0, cogs) : 0;
  const safeOpEx = isFinite(opEx) ? Math.max(0, opEx) : 0;
  const safeInterest = isFinite(interest) ? Math.max(0, interest) : 0;
  const safeTaxes = isFinite(taxes) ? Math.max(0, taxes) : 0;

  const grossProfit = safeRevenue - safeCogs;
  const operatingProfit = grossProfit - safeOpEx;
  const netProfit = operatingProfit - safeInterest - safeTaxes;
  const netMargin = safeRevenue > 0 ? (netProfit / safeRevenue) * 100 : 0;

  const chartData = [
    { name: "COGS", value: safeCogs },
    { name: "Operating Expenses", value: safeOpEx },
    { name: "Interest", value: safeInterest },
    { name: "Taxes", value: safeTaxes },
    { name: "Net Profit", value: Math.max(netProfit, 0) },
  ];

  return (
    <CalculatorLayout
      title="Net Profit Margin Calculator"
      description="Calculate net profit margin by breaking down revenue into COGS, operating expenses, interest, and taxes."
      icon={<span>📋</span>}
      results={
        <div className="space-y-4">
          <ResultCard label="Gross Profit" value={formatCurrency(grossProfit)} subtext="Revenue minus COGS" />
          <ResultCard label="Operating Profit" value={formatCurrency(operatingProfit)} subtext="Gross minus operating expenses" />
          <ResultCard label="Net Profit" value={formatCurrency(netProfit)} highlight />
          <ResultCard label="Net Profit Margin" value={formatPercentage(netMargin)} />
        </div>
      }
    >
      <CalculatorChart type="bar" data={chartData} xKey="name" yKey="value" title="Cost Breakdown" />
      <CalculatorInput input={{ id: "revenue", label: "Revenue", type: "number", defaultValue: 1000000, suffix: "$", min: 0, step: 1000, tooltip: "Total sales revenue generated by the business." }} value={revenue} onChange={setRevenue} />
      <CalculatorInput input={{ id: "cogs", label: "Cost of Goods Sold", type: "number", defaultValue: 600000, suffix: "$", min: 0, step: 1000, tooltip: "Direct costs of producing goods or services." }} value={cogs} onChange={setCogs} />
      <CalculatorInput input={{ id: "opEx", label: "Operating Expenses", type: "number", defaultValue: 200000, suffix: "$", min: 0, step: 1000, tooltip: "Salaries, rent, marketing, and other operating costs." }} value={opEx} onChange={setOpEx} />
      <CalculatorInput input={{ id: "interest", label: "Interest Expense", type: "number", defaultValue: 30000, suffix: "$", min: 0, step: 1000, tooltip: "Interest paid on loans and debt obligations." }} value={interest} onChange={setInterest} />
      <CalculatorInput input={{ id: "taxes", label: "Taxes", type: "number", defaultValue: 40000, suffix: "$", min: 0, step: 1000, tooltip: "Income taxes and other tax obligations." }} value={taxes} onChange={setTaxes} />
    </CalculatorLayout>
  );
}
