"use client";

import * as React from "react";
import { CalculatorLayout, CalculatorInput, CalculatorChart, ResultCard } from "..";
import { formatCurrency, formatPercentage } from "@/lib/utils";

export default function OperatingMarginCalculator() {
  const [revenue, setRevenue] = React.useState(1000000);
  const [cogs, setCogs] = React.useState(600000);
  const [sga, setSga] = React.useState(150000);
  const [rd, setRd] = React.useState(50000);
  const [da, setDa] = React.useState(30000);

  const safeRevenue = isFinite(revenue) ? Math.max(0, revenue) : 0;
  const safeCogs = isFinite(cogs) ? Math.max(0, cogs) : 0;
  const safeSga = isFinite(sga) ? Math.max(0, sga) : 0;
  const safeRd = isFinite(rd) ? Math.max(0, rd) : 0;
  const safeDa = isFinite(da) ? Math.max(0, da) : 0;

  const grossProfit = safeRevenue - safeCogs;
  const operatingIncome = grossProfit - safeSga - safeRd - safeDa;
  const operatingMargin = safeRevenue > 0 ? (operatingIncome / safeRevenue) * 100 : 0;

  const chartData = [
    { name: "COGS", value: safeCogs },
    { name: "SG&A", value: safeSga },
    { name: "R&D", value: safeRd },
    { name: "D&A", value: safeDa },
    { name: "Operating Income", value: Math.max(operatingIncome, 0) },
  ];

  return (
    <CalculatorLayout
      title="Operating Margin Calculator"
      description="Calculate operating income and operating margin from revenue and operating expense categories."
      icon={<span>⚙️</span>}
      results={
        <div className="space-y-4">
          <ResultCard label="Gross Profit" value={formatCurrency(grossProfit)} subtext="Revenue minus COGS" />
          <ResultCard label="Operating Income" value={formatCurrency(operatingIncome)} highlight />
          <ResultCard label="Operating Margin" value={formatPercentage(operatingMargin)} />
        </div>
      }
    >
      <CalculatorChart type="bar" data={chartData} xKey="name" yKey="value" title="Expense Categories" />
      <CalculatorInput input={{ id: "revenue", label: "Revenue", type: "number", defaultValue: 1000000, suffix: "$", min: 0, step: 1000, tooltip: "Total sales revenue generated by the business." }} value={revenue} onChange={setRevenue} />
      <CalculatorInput input={{ id: "cogs", label: "Cost of Goods Sold", type: "number", defaultValue: 600000, suffix: "$", min: 0, step: 1000, tooltip: "Direct costs of producing goods or services." }} value={cogs} onChange={setCogs} />
      <CalculatorInput input={{ id: "sga", label: "SG&A Expenses", type: "number", defaultValue: 150000, suffix: "$", min: 0, step: 1000, tooltip: "Selling, General & Administrative expenses." }} value={sga} onChange={setSga} />
      <CalculatorInput input={{ id: "rd", label: "R&D Expenses", type: "number", defaultValue: 50000, suffix: "$", min: 0, step: 1000, tooltip: "Research and Development expenses." }} value={rd} onChange={setRd} />
      <CalculatorInput input={{ id: "da", label: "D&A Expenses", type: "number", defaultValue: 30000, suffix: "$", min: 0, step: 1000, tooltip: "Depreciation & Amortization." }} value={da} onChange={setDa} />
    </CalculatorLayout>
  );
}
