"use client";

import * as React from "react";
import { CalculatorLayout, CalculatorInput, CalculatorChart, ResultCard, PeriodInput } from "..";
import type { PeriodUnit } from "..";
import { toPeriods } from "..";
import { formatCurrency } from "@/lib/utils";

export default function PaybackPeriodCalculator() {
  const [initialInvestment, setInitialInvestment] = React.useState(50000);
  const [annualCashFlow, setAnnualCashFlow] = React.useState(12000);
  const [timeHorizon, setTimeHorizon] = React.useState(50);
  const [timeHorizonUnit, setTimeHorizonUnit] = React.useState<PeriodUnit>("years");

  const safeInvestment = Math.max(0, initialInvestment ?? 0);
  const safeCashFlow = Math.max(0, annualCashFlow ?? 0);
  const maxYears = Math.max(1, Math.round(toPeriods(timeHorizon, timeHorizonUnit)));

  const evenPayback = safeCashFlow > 0 ? safeInvestment / safeCashFlow : Infinity;

  // DCF payback at 10% discount rate
  const discountRate = 10;
  const safeDiscountRate = discountRate / 100;
  let cumulativeDCF = -safeInvestment;
  let dcfPaybackYear = Infinity;
  for (let y = 1; y <= maxYears; y++) {
    const dcf = safeCashFlow / Math.pow(1 + safeDiscountRate, y);
    cumulativeDCF += dcf;
    if (cumulativeDCF >= 0) {
      const prevCumulative = cumulativeDCF - dcf;
      dcfPaybackYear = (y - 1) + Math.abs(prevCumulative) / dcf;
      break;
    }
  }

  // For even cash flows, simulate and show cumulative
  const years = Math.min(Math.ceil(evenPayback) + 5, maxYears);

  const chartData: { year: string; "Simple Payback": number; "Discounted Payback": number }[] = [];
  let cumulative = -safeInvestment;
  let dcfCumulative = -safeInvestment;
  chartData.push({ year: "Year 0", "Simple Payback": cumulative, "Discounted Payback": dcfCumulative });
  for (let y = 1; y <= Math.min(years, maxYears, 60); y++) {
    cumulative += safeCashFlow;
    dcfCumulative += safeCashFlow / Math.pow(1 + safeDiscountRate, y);
    chartData.push({
      year: `Year ${y}`,
      "Simple Payback": Math.round(cumulative * 100) / 100,
      "Discounted Payback": Math.round(dcfCumulative * 100) / 100,
    });
  }

  // Find exact payback year from cumulative data
  let paybackYear = 0;
  for (let y = 1; y <= years; y++) {
    const entry = chartData[y];
    if (entry && entry["Simple Payback"] >= 0) {
      const prevEntry = chartData[y - 1];
      const prevCumulative = prevEntry ? prevEntry["Simple Payback"] : -safeInvestment;
      const flowThisYear = safeCashFlow;
      paybackYear = (y - 1) + Math.abs(prevCumulative) / flowThisYear;
      break;
    }
  }

  return (
    <CalculatorLayout
      title="Payback Period Calculator"
      description="Calculate how long it will take to recover your initial investment from the cash flows generated by a project or investment."
      icon={<span>⏱️</span>}
      results={
        <div className="space-y-4">
          <ResultCard label="Payback Period" value={paybackYear > 0 ? `${paybackYear.toFixed(2)} years` : "N/A"} highlight subtext={paybackYear > 0 ? `Discounted: ${dcfPaybackYear === Infinity ? "N/A" : dcfPaybackYear.toFixed(2)} yrs` : undefined} />
          <ResultCard label="Initial Investment" value={formatCurrency(safeInvestment)} />
          <ResultCard label="Annual Cash Flow" value={formatCurrency(safeCashFlow)} />
          <ResultCard label="Discounted Payback" value={dcfPaybackYear === Infinity ? `>${maxYears} years` : `${dcfPaybackYear.toFixed(2)} years`} subtext={`At ${discountRate}% discount rate`} />
        </div>
      }
    >
      <CalculatorChart type="line" data={chartData} xKey="year" yKey={["Simple Payback", "Discounted Payback"]} title="Cumulative Cash Flow" />
      <CalculatorInput
        input={{ id: "initialInvestment", label: "Initial Investment", type: "number", defaultValue: 50000, suffix: "$", min: 0, step: 100, tooltip: "The upfront cost of the investment." }}
        value={initialInvestment}
        onChange={setInitialInvestment}
      />
      <CalculatorInput
        input={{ id: "annualCashFlow", label: "Annual Cash Flow", type: "number", defaultValue: 12000, suffix: "$", min: 0, step: 100, tooltip: "Expected annual cash inflow from the investment." }}
        value={annualCashFlow}
        onChange={setAnnualCashFlow}
      />
      <PeriodInput id="timeHorizon" label="Time Horizon" value={timeHorizon} unit={timeHorizonUnit} onValueChange={setTimeHorizon} onUnitChange={setTimeHorizonUnit} min={1} max={100} />
    </CalculatorLayout>
  );
}
