import type { CalculatorConfig, CategoryType } from "@/types/calculator";

export const allCalculators: CalculatorConfig[] = [
  {
    id: "basic-calculator",
    slug: "basic-calculator",
    title: "Basic Calculator",
    description: "Perform basic arithmetic operations including addition, subtraction, multiplication, and division.",
    category: "basic",
    icon: "🔢",
    color: "primary",
  },
  {
    id: "compound-interest",
    slug: "compound-interest",
    title: "Compound Interest",
    description: "Calculate compound interest with regular contributions, variable rates, and detailed growth charts.",
    category: "investment",
    icon: "📈",
    color: "accent",
  },
  {
    id: "simple-interest",
    slug: "simple-interest",
    title: "Simple Interest",
    description: "Calculate simple interest on loans and investments with clear principal and rate breakdowns.",
    category: "investment",
    icon: "💰",
    color: "primary",
  },
  {
    id: "investment-return",
    slug: "investment-return",
    title: "Investment Return",
    description: "Calculate total investment return including CAGR, absolute return, and annualized performance.",
    category: "investment",
    icon: "📊",
    color: "accent",
  },
  {
    id: "retirement-planning",
    slug: "retirement-planning",
    title: "Retirement Planning",
    description: "Plan your retirement savings with projections, withdrawal strategies, and goal tracking.",
    category: "retirement",
    icon: "🏖️",
    color: "accent",
  },
  {
    id: "401k-calculator",
    slug: "401k-calculator",
    title: "401(k) Calculator",
    description: "Estimate your 401(k) balance at retirement with employer match and contribution growth.",
    category: "retirement",
    icon: "🏦",
    color: "primary",
  },
  {
    id: "tax-calculator",
    slug: "tax-calculator",
    title: "Tax Calculator",
    description: "Estimate your income tax liability with marginal rate brackets and deductions.",
    category: "tax",
    icon: "📋",
    color: "primary",
  },
  {
    id: "capital-gains-tax",
    slug: "capital-gains-tax",
    title: "Capital Gains Tax",
    description: "Calculate capital gains tax on investments including short-term and long-term rates.",
    category: "tax",
    icon: "📑",
    color: "accent",
  },
  {
    id: "loan-calculator",
    slug: "loan-calculator",
    title: "Loan Calculator",
    description: "Calculate monthly payments, total interest, and amortization schedule for any loan.",
    category: "loan",
    icon: "🏦",
    color: "primary",
  },
  {
    id: "amortization-schedule",
    slug: "amortization-schedule",
    title: "Amortization Schedule",
    description: "Generate a complete amortization schedule with payment breakdown by principal and interest.",
    category: "loan",
    icon: "📅",
    color: "accent",
  },
  {
    id: "mortgage-calculator",
    slug: "mortgage-calculator",
    title: "Mortgage Calculator",
    description: "Estimate monthly mortgage payments including principal, interest, taxes, and insurance.",
    category: "mortgage",
    icon: "🏠",
    color: "primary",
  },
  {
    id: "mortgage-affordability",
    slug: "mortgage-affordability",
    title: "Mortgage Affordability",
    description: "Determine how much house you can afford based on income, debt, and down payment.",
    category: "mortgage",
    icon: "🔑",
    color: "accent",
  },
  {
    id: "roi-calculator",
    slug: "roi-calculator",
    title: "ROI Calculator",
    description: "Calculate return on investment with cost basis, gains, and annualized returns.",
    category: "business",
    icon: "📈",
    color: "primary",
  },
  {
    id: "break-even",
    slug: "break-even",
    title: "Break-Even Analysis",
    description: "Calculate the break-even point for your business with fixed and variable costs.",
    category: "business",
    icon: "⚖️",
    color: "accent",
  },
  {
    id: "budget-planner",
    slug: "budget-planner",
    title: "Budget Planner",
    description: "Create and analyze a personal budget with income, expenses, and savings goals.",
    category: "personal",
    icon: "📒",
    color: "primary",
  },
  {
    id: "net-worth",
    slug: "net-worth",
    title: "Net Worth Calculator",
    description: "Track your net worth by adding assets and liabilities with real-time totals.",
    category: "personal",
    icon: "💎",
    color: "accent",
  },
  {
    id: "savings-goal",
    slug: "savings-goal",
    title: "Savings Goal",
    description: "Plan your savings goals with monthly contributions and time-to-target projections.",
    category: "personal",
    icon: "🎯",
    color: "primary",
  },
  {
    id: "inflation-calculator",
    slug: "inflation-calculator",
    title: "Inflation Calculator",
    description: "Calculate the future value of money adjusted for inflation over time.",
    category: "basic",
    icon: "📉",
    color: "accent",
  },
  {
    id: "currency-converter",
    slug: "currency-converter",
    title: "Currency Converter",
    description: "Convert between different currencies with live exchange rates.",
    category: "basic",
    icon: "💱",
    color: "primary",
  },
  {
    id: "tip-calculator",
    slug: "tip-calculator",
    title: "Tip Calculator",
    description: "Calculate the appropriate tip amount and split the bill among multiple people.",
    category: "personal",
    icon: "🍽️",
    color: "accent",
  },
  {
    id: "discount-calculator",
    slug: "discount-calculator",
    title: "Discount Calculator",
    description: "Calculate discounted prices, savings amounts, and final sale prices.",
    category: "basic",
    icon: "🏷️",
    color: "primary",
  },
  {
    id: "salary-calculator",
    slug: "salary-calculator",
    title: "Salary Calculator",
    description: "Convert between hourly, weekly, monthly, and annual salary figures.",
    category: "personal",
    icon: "💼",
    color: "accent",
  },
  {
    id: "stock-return",
    slug: "stock-return",
    title: "Stock Return Calculator",
    description: "Calculate total stock returns including dividends, price appreciation, and total yield.",
    category: "investment",
    icon: "📉",
    color: "primary",
  },
  {
    id: "dividend-calculator",
    slug: "dividend-calculator",
    title: "Dividend Calculator",
    description: "Project dividend income with DRIP, growth rates, and reinvestment strategies.",
    category: "investment",
    icon: "💵",
    color: "accent",
  },
  {
    id: "dollar-cost-average",
    slug: "dollar-cost-average",
    title: "Dollar Cost Average",
    description: "Calculate the average cost basis of periodic investments in a single security.",
    category: "investment",
    icon: "📊",
    color: "primary",
  },
  // ---- Loan Calculators (New) ----
  {
    id: "auto-loan",
    slug: "auto-loan",
    title: "Auto Loan Calculator",
    description: "Calculate monthly payments, total interest, and total cost for car loans with various terms.",
    category: "loan",
    icon: "🚗",
    color: "primary",
  },
  {
    id: "student-loan",
    slug: "student-loan",
    title: "Student Loan Calculator",
    description: "Plan student loan repayment with income-based options, consolidation, and payoff projections.",
    category: "loan",
    icon: "🎓",
    color: "accent",
  },
  {
    id: "personal-loan",
    slug: "personal-loan",
    title: "Personal Loan Calculator",
    description: "Estimate monthly payments and total interest for personal loans with fixed terms.",
    category: "loan",
    icon: "💳",
    color: "primary",
  },
  {
    id: "debt-consolidation",
    slug: "debt-consolidation",
    title: "Debt Consolidation Calculator",
    description: "Compare consolidation options and see how combining debts affects interest and payoff time.",
    category: "loan",
    icon: "🔗",
    color: "accent",
  },
  {
    id: "loan-comparison",
    slug: "loan-comparison",
    title: "Loan Comparison",
    description: "Compare multiple loan offers side by side with rates, fees, and total cost analysis.",
    category: "loan",
    icon: "⚖️",
    color: "primary",
  },
  {
    id: "debt-payoff",
    slug: "debt-payoff",
    title: "Debt Payoff Calculator",
    description: "Calculate how long it will take to pay off debt with various monthly payment strategies.",
    category: "loan",
    icon: "💪",
    color: "accent",
  },
  {
    id: "debt-snowball",
    slug: "debt-snowball",
    title: "Debt Snowball Method",
    description: "Pay off debts from smallest to largest balance using the snowball method for momentum.",
    category: "loan",
    icon: "❄️",
    color: "primary",
  },
  {
    id: "debt-avalanche",
    slug: "debt-avalanche",
    title: "Debt Avalanche Method",
    description: "Pay off debts from highest to lowest interest rate using the avalanche method to save on interest.",
    category: "loan",
    icon: "⛰️",
    color: "accent",
  },
  {
    id: "loan-refinancing",
    slug: "loan-refinancing",
    title: "Loan Refinancing Calculator",
    description: "Evaluate whether refinancing a loan makes sense by comparing new vs. current terms.",
    category: "loan",
    icon: "🔄",
    color: "primary",
  },
  {
    id: "lease-vs-buy",
    slug: "lease-vs-buy",
    title: "Lease vs. Buy Calculator",
    description: "Compare the total cost of leasing versus buying a vehicle or asset over time.",
    category: "loan",
    icon: "🏷️",
    color: "accent",
  },
  // ---- Mortgage Calculators (New) ----
  {
    id: "refinance-calculator",
    slug: "refinance-calculator",
    title: "Refinance Calculator",
    description: "Determine if refinancing your mortgage is worthwhile with break-even and savings analysis.",
    category: "mortgage",
    icon: "🔄",
    color: "primary",
  },
  {
    id: "rent-vs-buy",
    slug: "rent-vs-buy",
    title: "Rent vs. Buy Calculator",
    description: "Compare the financial outcomes of renting versus buying a home over any time horizon.",
    category: "mortgage",
    icon: "🏘️",
    color: "accent",
  },
  {
    id: "home-equity",
    slug: "home-equity",
    title: "Home Equity Calculator",
    description: "Calculate your home equity, loan-to-value ratio, and available equity for borrowing.",
    category: "mortgage",
    icon: "📊",
    color: "primary",
  },
  {
    id: "closing-costs",
    slug: "closing-costs",
    title: "Closing Costs Calculator",
    description: "Estimate total closing costs for buying or refinancing a home including fees and taxes.",
    category: "mortgage",
    icon: "📋",
    color: "accent",
  },
  {
    id: "mortgage-payoff",
    slug: "mortgage-payoff",
    title: "Mortgage Payoff Calculator",
    description: "Calculate how extra payments can shorten your mortgage term and reduce total interest.",
    category: "mortgage",
    icon: "🏁",
    color: "primary",
  },
  {
    id: "biweekly-mortgage",
    slug: "biweekly-mortgage",
    title: "Biweekly Mortgage Calculator",
    description: "Compare biweekly payment schedules against standard monthly payments and see interest savings.",
    category: "mortgage",
    icon: "📅",
    color: "accent",
  },
  {
    id: "fha-loan",
    slug: "fha-loan",
    title: "FHA Loan Calculator",
    description: "Estimate monthly payments and MIP costs for FHA-insured home loans.",
    category: "mortgage",
    icon: "🏛️",
    color: "primary",
  },
  {
    id: "va-loan",
    slug: "va-loan",
    title: "VA Loan Calculator",
    description: "Calculate monthly payments and funding fee for VA-guaranteed home loans.",
    category: "mortgage",
    icon: "🎖️",
    color: "accent",
  },
  {
    id: "arm-calculator",
    slug: "arm-calculator",
    title: "ARM Calculator",
    description: "Project adjustable-rate mortgage payments with rate caps, indexes, and adjustment periods.",
    category: "mortgage",
    icon: "📈",
    color: "primary",
  },
  {
    id: "pmi-calculator",
    slug: "pmi-calculator",
    title: "PMI Calculator",
    description: "Calculate private mortgage insurance costs and when PMI will automatically terminate.",
    category: "mortgage",
    icon: "🛡️",
    color: "accent",
  },
  {
    id: "home-renovation",
    slug: "home-renovation",
    title: "Home Renovation Calculator",
    description: "Budget home renovation projects with material costs, labor estimates, and ROI projections.",
    category: "mortgage",
    icon: "🔨",
    color: "primary",
  },
  // ---- Investment Calculators (New) ----
  {
    id: "portfolio-allocator",
    slug: "portfolio-allocator",
    title: "Portfolio Allocator",
    description: "Design and analyze asset allocation strategies across stocks, bonds, and alternative investments.",
    category: "investment",
    icon: "📊",
    color: "primary",
  },
  {
    id: "risk-reward",
    slug: "risk-reward",
    title: "Risk/Reward Calculator",
    description: "Calculate the risk-reward ratio for trades and investments to evaluate potential opportunities.",
    category: "investment",
    icon: "🎯",
    color: "accent",
  },
  {
    id: "position-sizing",
    slug: "position-sizing",
    title: "Position Sizing Calculator",
    description: "Determine optimal position sizes based on account risk, stop-loss, and portfolio allocation rules.",
    category: "investment",
    icon: "📏",
    color: "primary",
  },
  {
    id: "option-profit",
    slug: "option-profit",
    title: "Option Profit Calculator",
    description: "Calculate potential profit and loss for option strategies including calls, puts, and spreads.",
    category: "investment",
    icon: "📉",
    color: "accent",
  },
  {
    id: "bond-yield",
    slug: "bond-yield",
    title: "Bond Yield Calculator",
    description: "Calculate current yield, yield to maturity, and yield to call for bonds and fixed-income securities.",
    category: "investment",
    icon: "💵",
    color: "primary",
  },
  {
    id: "bond-price",
    slug: "bond-price",
    title: "Bond Price Calculator",
    description: "Calculate the fair price of a bond given its coupon rate, yield, maturity, and face value.",
    category: "investment",
    icon: "🏷️",
    color: "accent",
  },
  {
    id: "capm-calculator",
    slug: "capm-calculator",
    title: "CAPM Calculator",
    description: "Calculate the expected return of an asset using the Capital Asset Pricing Model with beta and risk-free rate.",
    category: "investment",
    icon: "📐",
    color: "primary",
  },
  {
    id: "sharpe-ratio",
    slug: "sharpe-ratio",
    title: "Sharpe Ratio Calculator",
    description: "Calculate the risk-adjusted return of an investment using the Sharpe ratio formula.",
    category: "investment",
    icon: "📏",
    color: "accent",
  },
  {
    id: "alpha-calculator",
    slug: "alpha-calculator",
    title: "Alpha Calculator",
    description: "Calculate Jensen's alpha to measure an investment's excess return relative to its benchmark.",
    category: "investment",
    icon: "🔤",
    color: "primary",
  },
  {
    id: "beta-calculator",
    slug: "beta-calculator",
    title: "Beta Calculator",
    description: "Calculate the beta coefficient to measure a stock's volatility relative to the market.",
    category: "investment",
    icon: "β",
    color: "accent",
  },
  {
    id: "asset-correlation",
    slug: "asset-correlation",
    title: "Asset Correlation Calculator",
    description: "Calculate the correlation coefficient between two assets to assess diversification benefits.",
    category: "investment",
    icon: "🔄",
    color: "primary",
  },
  {
    id: "monte-carlo-simulation",
    slug: "monte-carlo-simulation",
    title: "Monte Carlo Simulation",
    description: "Run thousands of investment simulations to model probable portfolio outcomes and risk scenarios.",
    category: "investment",
    icon: "🎲",
    color: "accent",
  },
  {
    id: "annuity-calculator",
    slug: "annuity-calculator",
    title: "Annuity Calculator",
    description: "Calculate the future value of an annuity with regular payments and compounding interest.",
    category: "investment",
    icon: "📋",
    color: "primary",
  },
  {
    id: "perpetuity-calculator",
    slug: "perpetuity-calculator",
    title: "Perpetuity Calculator",
    description: "Calculate the present value of a perpetuity with constant or growing cash flows.",
    category: "investment",
    icon: "♾️",
    color: "accent",
  },
  {
    id: "present-value",
    slug: "present-value",
    title: "Present Value Calculator",
    description: "Calculate the present value of future cash flows discounted at a given rate.",
    category: "investment",
    icon: "💲",
    color: "primary",
  },
  {
    id: "future-value",
    slug: "future-value",
    title: "Future Value Calculator",
    description: "Calculate the future value of an investment with compound interest and periodic contributions.",
    category: "investment",
    icon: "🔮",
    color: "accent",
  },
  {
    id: "irr-calculator",
    slug: "irr-calculator",
    title: "IRR Calculator",
    description: "Calculate the internal rate of return for a series of cash flows to evaluate investment profitability.",
    category: "investment",
    icon: "📈",
    color: "primary",
  },
  {
    id: "npv-calculator",
    slug: "npv-calculator",
    title: "NPV Calculator",
    description: "Calculate the net present value of projected cash flows to assess investment viability.",
    category: "investment",
    icon: "💰",
    color: "accent",
  },
  {
    id: "payback-period",
    slug: "payback-period",
    title: "Payback Period Calculator",
    description: "Calculate how long it takes to recover an initial investment from expected cash flows.",
    category: "investment",
    icon: "⏱️",
    color: "primary",
  },
  {
    id: "financial-ratios",
    slug: "financial-ratios",
    title: "Financial Ratios Calculator",
    description: "Compute key financial ratios including P/E, P/B, debt-to-equity, and return on equity.",
    category: "investment",
    icon: "📊",
    color: "accent",
  },
  // ---- Retirement Calculators (New) ----
  {
    id: "roth-ira",
    slug: "roth-ira",
    title: "Roth IRA Calculator",
    description: "Project Roth IRA growth with after-tax contributions, tax-free withdrawals, and contribution limits.",
    category: "retirement",
    icon: "🪙",
    color: "primary",
  },
  {
    id: "traditional-ira",
    slug: "traditional-ira",
    title: "Traditional IRA Calculator",
    description: "Estimate traditional IRA growth with tax-deductible contributions and taxable withdrawals.",
    category: "retirement",
    icon: "🏛️",
    color: "accent",
  },
  {
    id: "social-security",
    slug: "social-security",
    title: "Social Security Calculator",
    description: "Estimate your Social Security benefits based on earnings history and claiming age.",
    category: "retirement",
    icon: "🆔",
    color: "primary",
  },
  {
    id: "pension-calculator",
    slug: "pension-calculator",
    title: "Pension Calculator",
    description: "Calculate projected pension income based on years of service, salary, and payout options.",
    category: "retirement",
    icon: "🏦",
    color: "accent",
  },
  {
    id: "retirement-withdrawal",
    slug: "retirement-withdrawal",
    title: "Retirement Withdrawal Calculator",
    description: "Plan sustainable retirement withdrawals using the 4% rule and dynamic spending strategies.",
    category: "retirement",
    icon: "🏧",
    color: "primary",
  },
  {
    id: "required-minimum-distribution",
    slug: "required-minimum-distribution",
    title: "RMD Calculator",
    description: "Calculate required minimum distributions from retirement accounts based on IRS life expectancy tables.",
    category: "retirement",
    icon: "📋",
    color: "accent",
  },
  {
    id: "retirement-income",
    slug: "retirement-income",
    title: "Retirement Income Calculator",
    description: "Project total retirement income from multiple sources including savings, pensions, and Social Security.",
    category: "retirement",
    icon: "💵",
    color: "primary",
  },
  {
    id: "early-retirement",
    slug: "early-retirement",
    title: "Early Retirement Calculator",
    description: "Determine if you can retire early using the FIRE method with savings rate and withdrawal strategies.",
    category: "retirement",
    icon: "🔥",
    color: "accent",
  },
  {
    id: "retirement-expenses",
    slug: "retirement-expenses",
    title: "Retirement Expenses Calculator",
    description: "Estimate your retirement living expenses including healthcare, housing, and lifestyle costs.",
    category: "retirement",
    icon: "💰",
    color: "primary",
  },
  // ---- Tax Calculators (New) ----
  {
    id: "sales-tax",
    slug: "sales-tax",
    title: "Sales Tax Calculator",
    description: "Calculate sales tax amounts and total purchase prices for any state or local tax rate.",
    category: "tax",
    icon: "🧾",
    color: "primary",
  },
  {
    id: "property-tax",
    slug: "property-tax",
    title: "Property Tax Calculator",
    description: "Estimate annual property taxes based on home value, assessment rate, and local millage rates.",
    category: "tax",
    icon: "🏠",
    color: "accent",
  },
  {
    id: "estate-tax",
    slug: "estate-tax",
    title: "Estate Tax Calculator",
    description: "Calculate potential federal and state estate tax liability based on estate value and exemptions.",
    category: "tax",
    icon: "📜",
    color: "primary",
  },
  {
    id: "inheritance-tax",
    slug: "inheritance-tax",
    title: "Inheritance Tax Calculator",
    description: "Estimate inheritance tax owed by beneficiaries based on state laws and relationship tiers.",
    category: "tax",
    icon: "📑",
    color: "accent",
  },
  {
    id: "self-employment-tax",
    slug: "self-employment-tax",
    title: "Self-Employment Tax Calculator",
    description: "Calculate self-employment tax including Social Security and Medicare contributions for freelancers.",
    category: "tax",
    icon: "💼",
    color: "primary",
  },
  {
    id: "effective-tax-rate",
    slug: "effective-tax-rate",
    title: "Effective Tax Rate Calculator",
    description: "Calculate your overall effective tax rate by dividing total tax liability by total income.",
    category: "tax",
    icon: "📊",
    color: "accent",
  },
  {
    id: "marginal-tax-rate",
    slug: "marginal-tax-rate",
    title: "Marginal Tax Rate Calculator",
    description: "Determine your marginal tax bracket and see how additional income would be taxed.",
    category: "tax",
    icon: "📈",
    color: "primary",
  },
  {
    id: "tax-bracket",
    slug: "tax-bracket",
    title: "Tax Bracket Calculator",
    description: "Find your federal income tax bracket and calculate taxes owed at each bracket level.",
    category: "tax",
    icon: "📋",
    color: "accent",
  },
  {
    id: "w4-calculator",
    slug: "w4-calculator",
    title: "W-4 Calculator",
    description: "Optimize your W-4 withholding allowances to get the right tax refund or amount due.",
    category: "tax",
    icon: "📝",
    color: "primary",
  },
  {
    id: "1099-calculator",
    slug: "1099-calculator",
    title: "1099 Calculator",
    description: "Estimate quarterly tax payments and total tax burden for 1099 independent contractors.",
    category: "tax",
    icon: "📄",
    color: "accent",
  },
  // ---- Business Calculators (New) ----
  {
    id: "gross-margin",
    slug: "gross-margin",
    title: "Gross Margin Calculator",
    description: "Calculate gross profit margin by subtracting cost of goods sold from total revenue.",
    category: "business",
    icon: "📊",
    color: "primary",
  },
  {
    id: "net-profit-margin",
    slug: "net-profit-margin",
    title: "Net Profit Margin Calculator",
    description: "Calculate net profit margin after all expenses, taxes, and costs are deducted from revenue.",
    category: "business",
    icon: "💵",
    color: "accent",
  },
  {
    id: "markup-calculator",
    slug: "markup-calculator",
    title: "Markup Calculator",
    description: "Calculate selling price, markup percentage, and profit margin from cost and desired markup.",
    category: "business",
    icon: "🏷️",
    color: "primary",
  },
  {
    id: "margin-calculator",
    slug: "margin-calculator",
    title: "Margin Calculator",
    description: "Calculate profit margin, revenue, and cost of goods sold from any two known values.",
    category: "business",
    icon: "📐",
    color: "accent",
  },
  {
    id: "operating-margin",
    slug: "operating-margin",
    title: "Operating Margin Calculator",
    description: "Calculate operating profit margin by subtracting operating expenses from gross profit.",
    category: "business",
    icon: "⚙️",
    color: "primary",
  },
  {
    id: "cash-flow",
    slug: "cash-flow",
    title: "Cash Flow Calculator",
    description: "Analyze business cash flow by tracking operating, investing, and financing activities.",
    category: "business",
    icon: "💧",
    color: "accent",
  },
  {
    id: "dcf-analysis",
    slug: "dcf-analysis",
    title: "DCF Analysis",
    description: "Perform discounted cash flow valuation by projecting future cash flows and discounting to present value.",
    category: "business",
    icon: "📈",
    color: "primary",
  },
  {
    id: "inventory-turnover",
    slug: "inventory-turnover",
    title: "Inventory Turnover Calculator",
    description: "Calculate inventory turnover ratio and days in inventory to measure supply chain efficiency.",
    category: "business",
    icon: "📦",
    color: "accent",
  },
  {
    id: "customer-acquisition-cost",
    slug: "customer-acquisition-cost",
    title: "CAC Calculator",
    description: "Calculate customer acquisition cost by dividing total sales and marketing spend by new customers.",
    category: "business",
    icon: "🎯",
    color: "primary",
  },
  {
    id: "lifetime-value",
    slug: "lifetime-value",
    title: "LTV Calculator",
    description: "Calculate customer lifetime value using average purchase value, frequency, and retention rate.",
    category: "business",
    icon: "💎",
    color: "accent",
  },
  // ---- Personal Finance Calculators (New) ----
  {
    id: "em-fund",
    slug: "em-fund",
    title: "Emergency Fund Calculator",
    description: "Determine how much you need in your emergency fund based on monthly expenses and job stability.",
    category: "personal",
    icon: "🆘",
    color: "primary",
  },
  {
    id: "debt-to-income",
    slug: "debt-to-income",
    title: "Debt-to-Income Ratio Calculator",
    description: "Calculate your debt-to-income ratio to assess borrowing capacity and financial health.",
    category: "personal",
    icon: "📊",
    color: "accent",
  },
  {
    id: "credit-card-payoff",
    slug: "credit-card-payoff",
    title: "Credit Card Payoff Calculator",
    description: "Calculate how long it will take to pay off credit card debt with different payment strategies.",
    category: "personal",
    icon: "💳",
    color: "primary",
  },
  {
    id: "college-savings",
    slug: "college-savings",
    title: "College Savings Calculator",
    description: "Plan for education costs with 529 plans, savings projections, and future tuition estimates.",
    category: "personal",
    icon: "🎓",
    color: "accent",
  },
  {
    id: "car-affordability",
    slug: "car-affordability",
    title: "Car Affordability Calculator",
    description: "Determine how much car you can afford based on income, existing debts, and down payment.",
    category: "personal",
    icon: "🚗",
    color: "primary",
  },
  {
    id: "insurance-needs",
    slug: "insurance-needs",
    title: "Insurance Needs Calculator",
    description: "Estimate how much life and disability insurance coverage you need based on your financial situation.",
    category: "personal",
    icon: "🛡️",
    color: "accent",
  },
  {
    id: "child-care-cost",
    slug: "child-care-cost",
    title: "Child Care Cost Calculator",
    description: "Calculate annual child care expenses including daycare, nannies, and after-school programs.",
    category: "personal",
    icon: "👶",
    color: "primary",
  },
  {
    id: "moving-cost",
    slug: "moving-cost",
    title: "Moving Cost Calculator",
    description: "Estimate moving expenses including truck rental, packing supplies, movers, and travel costs.",
    category: "personal",
    icon: "📦",
    color: "accent",
  },
  {
    id: "wedding-budget",
    slug: "wedding-budget",
    title: "Wedding Budget Calculator",
    description: "Plan your wedding budget with category breakdowns, vendor costs, and guest count tracking.",
    category: "personal",
    icon: "💍",
    color: "primary",
  },
  {
    id: "vacation-budget",
    slug: "vacation-budget",
    title: "Vacation Budget Calculator",
    description: "Plan trip expenses including flights, accommodation, meals, activities, and contingency funds.",
    category: "personal",
    icon: "✈️",
    color: "accent",
  },
  {
    id: "side-hustle-calculator",
    slug: "side-hustle-calculator",
    title: "Side Hustle Calculator",
    description: "Calculate actual hourly earnings from side gigs after expenses, taxes, and time invested.",
    category: "personal",
    icon: "💪",
    color: "primary",
  },
  {
    id: "fica-calculator",
    slug: "fica-calculator",
    title: "FICA Calculator",
    description: "Calculate FICA tax contributions including Social Security and Medicare withholdings.",
    category: "personal",
    icon: "📋",
    color: "accent",
  },
  {
    id: "hourly-to-salary",
    slug: "hourly-to-salary",
    title: "Hourly to Salary Converter",
    description: "Convert hourly wages to annual salary and compare compensation across different pay periods.",
    category: "personal",
    icon: "⏰",
    color: "primary",
  },
  {
    id: "overtime-calculator",
    slug: "overtime-calculator",
    title: "Overtime Calculator",
    description: "Calculate overtime pay with time-and-a-half, double-time, and other overtime rate structures.",
    category: "personal",
    icon: "🕐",
    color: "accent",
  },
  {
    id: "paycheck-calculator",
    slug: "paycheck-calculator",
    title: "Paycheck Calculator",
    description: "Estimate your take-home pay after federal, state, and local taxes and other deductions.",
    category: "personal",
    icon: "💵",
    color: "primary",
  },
  // ---- Basic Calculators (New) ----
  {
    id: "percentage-calculator",
    slug: "percentage-calculator",
    title: "Percentage Calculator",
    description: "Calculate percentages, percentage change, and percentage of any number with ease.",
    category: "basic",
    icon: "💯",
    color: "primary",
  },
  {
    id: "bmi-calculator",
    slug: "bmi-calculator",
    title: "BMI Calculator",
    description: "Calculate your Body Mass Index and see which weight category you fall into.",
    category: "basic",
    icon: "⚖️",
    color: "accent",
  },
  {
    id: "calorie-calculator",
    slug: "calorie-calculator",
    title: "Calorie Calculator",
    description: "Estimate daily calorie needs based on age, gender, weight, height, and activity level.",
    category: "basic",
    icon: "🔥",
    color: "primary",
  },
  {
    id: "date-difference",
    slug: "date-difference",
    title: "Date Difference Calculator",
    description: "Calculate the exact number of days, weeks, months, or years between any two dates.",
    category: "basic",
    icon: "📅",
    color: "accent",
  },
  {
    id: "age-calculator",
    slug: "age-calculator",
    title: "Age Calculator",
    description: "Calculate your exact age in years, months, days, hours, and minutes from any birth date.",
    category: "basic",
    icon: "🎂",
    color: "primary",
  },
  {
    id: "time-value-of-money",
    slug: "time-value-of-money",
    title: "Time Value of Money",
    description: "Calculate present and future values with TVM principles including compounding and discounting.",
    category: "basic",
    icon: "⏳",
    color: "accent",
  },
  {
    id: "rule-of-72",
    slug: "rule-of-72",
    title: "Rule of 72 Calculator",
    description: "Estimate how long it takes for an investment to double using the Rule of 72 formula.",
    category: "basic",
    icon: "📐",
    color: "primary",
  },
  {
    id: "fraction-calculator",
    slug: "fraction-calculator",
    title: "Fraction Calculator",
    description: "Perform arithmetic operations on fractions with simplification and mixed number conversion.",
    category: "basic",
    icon: "➗",
    color: "accent",
  },
  {
    id: "unit-converter",
    slug: "unit-converter",
    title: "Unit Converter",
    description: "Convert between units of length, mass, volume, temperature, area, and speed.",
    category: "basic",
    icon: "📏",
    color: "primary",
  },
  {
    id: "gas-mileage",
    slug: "gas-mileage",
    title: "Gas Mileage Calculator",
    description: "Calculate miles per gallon, fuel efficiency, and trip fuel costs for any vehicle.",
    category: "basic",
    icon: "⛽",
    color: "accent",
  },
  {
    id: "fuel-cost",
    slug: "fuel-cost",
    title: "Fuel Cost Calculator",
    description: "Estimate total fuel costs for a trip based on distance, vehicle efficiency, and fuel price.",
    category: "basic",
    icon: "⛽",
    color: "primary",
  },
  {
    id: "electricity-cost",
    slug: "electricity-cost",
    title: "Electricity Cost Calculator",
    description: "Calculate the cost of running electrical appliances based on wattage, hours used, and rates.",
    category: "basic",
    icon: "💡",
    color: "accent",
  },
  {
    id: "water-bill",
    slug: "water-bill",
    title: "Water Bill Calculator",
    description: "Estimate monthly water bills based on usage in gallons and local utility rate structures.",
    category: "basic",
    icon: "💧",
    color: "primary",
  },
  {
    id: "phone-plan-comparison",
    slug: "phone-plan-comparison",
    title: "Phone Plan Comparison",
    description: "Compare mobile phone plans by cost, data allowance, coverage, and contract terms side by side.",
    category: "basic",
    icon: "📱",
    color: "accent",
  },
];

export function getCalculatorBySlug(slug: string): CalculatorConfig | undefined {
  return allCalculators.find((c) => c.slug === slug);
}

export function getCalculatorsByCategory(
  category: CategoryType,
): CalculatorConfig[] {
  return allCalculators.filter((c) => c.category === category);
}

export function getAllCategories(): CategoryType[] {
  const categories = new Set(allCalculators.map((c) => c.category));
  return Array.from(categories);
}
