#!/usr/bin/env python3
"""Insert 5 targeted blog posts into posts.ts"""
import re

with open('/home/admin1/qfinhub/src/lib/blog/posts.ts') as f:
    content = f.read()

pos = content.rfind('\n];')
print(f"Slugs before: {content.count('slug:')}")

entries = [
    '  {\n  slug: "20000-loan-5-years-8-percent-monthly-payment",\n  title: "$20,000 Loan for 5 Years at 8%: Your Monthly Payment Is $405.53",\n  description: "Borrowing $20,000 for 5 years at 8% APR? Your monthly payment is $405.53. Use our free loan calculator to get your exact payment and full amortization schedule.",\n  category: "loans",\n  publishedAt: new Date("2026-05-23"),\n  readingTime: 6,\n  relatedCalculators: ["loan-calculator", "amortization-schedule", "debt-snowball"],\n  content: `<h2>Your Monthly Payment: $405.53</h2><p>If you borrow $20,000 for 5 years at an annual interest rate of 8%, your monthly payment is <strong>$405.53</strong>. Over the 60-month term, you will pay a total of $24,331.80, which includes $4,331.80 in interest. Use our <a href="https://www.qfinhub.com/calculators/loan-calculator" target="_blank">free loan calculator</a> to adjust the numbers for your specific situation and see a complete amortization schedule.</p><h2>How We Calculated This</h2><p>The fixed monthly payment for any installment loan uses this formula: M = P [r(1+r)^n] / [(1+r)^n - 1]. Where P = principal ($20,000), r = monthly interest rate (8%/12 = 0.006667), and n = total payments (60). Plugging in: M = 20000 x 0.0202765 = $405.53. Use our <a href="https://www.qfinhub.com/calculators/loan-calculator" target="_blank">loan calculator</a> to do this math instantly.</p><h2>Amortization Breakdown</h2><p>In month 1, $133.33 goes to interest and $272.20 to principal. By month 60, only $2.68 goes to interest and $402.85 to principal. View your full schedule with our <a href="https://www.qfinhub.com/calculators/amortization-schedule" target="_blank">amortization calculator</a>.</p><h2>How Rate Changes Affect Payment</h2><ul><li><strong>6%:</strong> $386.66/month, total interest $3,199</li><li><strong>10%:</strong> $424.94/month, total interest $5,496</li><li><strong>3-year term:</strong> $626.73/month, total interest $2,562</li></ul><p>Use our <a href="https://www.qfinhub.com/calculators/loan-calculator" target="_blank">loan calculator</a> to test any combination. Shop 3+ lenders — a 1% rate difference saves $10.84/month.</p><h2>FAQ</h2><p><strong>Q: Total interest on $20K at 8% for 5 years?</strong><br>A: $4,331.80, making total repayment $24,331.80.</p><p><strong>Q: Can I pay off early?</strong><br>A: Most personal loans allow it. $50 extra/month saves $566 in interest and pays off 8 months early.</p>`,\n  }',

    '  {\n  slug: "200k-mortgage-payment-30-years",\n  title: "$200,000 Mortgage Payment for 30 Years: Exact Monthly Cost",\n  description: "Wondering what is the monthly payment on a $200,000 mortgage for 30 years? At 6.5% APR it is $1,264/month. Use our free mortgage calculator for your exact rate and full breakdown.",\n  category: "mortgage",\n  publishedAt: new Date("2026-05-23"),\n  readingTime: 7,\n  relatedCalculators: ["mortgage-calculator", "amortization-schedule", "mortgage-affordability"],\n  content: `<h2>Your Payment: $1,264.14 at 6.5%</h2><p>On a $200,000 mortgage for 30 years at 6.5% interest, your monthly principal and interest payment is <strong>$1,264.14</strong>. Over 30 years you will pay $255,090 in total interest. With property taxes (~$200/month) and insurance (~$100/month), total monthly housing cost is approximately $1,564. Use our <a href="https://www.qfinhub.com/calculators/mortgage-calculator" target="_blank">free mortgage calculator</a> for your exact rate.</p><h2>How the Payment Is Calculated</h2><p>Formula: M = P [r(1+r)^n] / [(1+r)^n - 1]. P = $200,000, r = 0.065/12 = 0.0054167, n = 360. M = 200000 x 0.0063207 = $1,264.14. Total including interest: $455,090.</p><h2>Payment at Different Rates</h2><ul><li><strong>5.5%:</strong> $1,135.58 — interest: $208,809</li><li><strong>6.0%:</strong> $1,199.10 — interest: $231,676</li><li><strong>6.5%:</strong> $1,264.14 — interest: $255,090</li><li><strong>7.0%:</strong> $1,330.60 — interest: $279,016</li></ul><p>A 0.5% rate change = ~$65/month difference and $23,000+ in total interest. Use our <a href="https://www.qfinhub.com/calculators/mortgage-calculator" target="_blank">mortgage calculator</a> to compare rates.</p><h2>15-Year Option</h2><p>At 6.5%, a 15-year loan on $200K has a $1,742 payment but saves $141,492 in total interest vs 30-year. Use our <a href="https://www.qfinhub.com/calculators/amortization-schedule" target="_blank">amortization calculator</a>.</p><h2>FAQ</h2><p><strong>Q: Income needed for $200K mortgage?</strong><br>A: With 28% rule, you need ~$54,180/year for P&I alone, or ~$70,000 with taxes/insurance.</p><p><strong>Q: Points worth it?</strong><br>A: One point ($2,000) saves ~$32/month. Break-even: 63 months. Worth it if staying 6+ years.</p>`,\n  }',

    '  {\n  slug: "retire-by-40-calculator-how-much-needed",\n  title: "Retire by 40 Calculator: How Much Do You Need Saved?",\n  description: "Want to retire by 40? For $50K/year retirement income at age 40, you need $1.25M-$1.67M invested. Get your FIRE number with our free calculator.",\n  category: "retirement",\n  publishedAt: new Date("2026-05-23"),\n  readingTime: 7,\n  relatedCalculators: ["financial-independence", "retirement-planning", "compound-interest"],\n  content: `<h2>Retire by 40: You Need $1.25M-$1.67M</h2><p>To retire at age 40 with $50,000 annual spending, you need <strong>$1.25 million to $1.67 million</strong> invested. Using the 4% rule: $50,000 / 0.04 = $1.25M. Using a conservative 3% rate for 50+ year retirement: $1.67M. Use our <a href="https://www.qfinhub.com/calculators/financial-independence" target="_blank">free FIRE calculator</a> for your exact number with your expenses and withdrawal rate.</p><h2>The FIRE Formula</h2><p>FIRE Number = Annual Expenses / Safe Withdrawal Rate. SWR is typically 3-4%. For 40+ year retirements, 3-3.5% is recommended. $40K/year needs $1.14M at 3.5%. $60K/year needs $1.71M. Use our <a href="https://www.qfinhub.com/calculators/retirement-planning" target="_blank">retirement calculator</a> to model scenarios.</p><h2>Monthly Savings Required</h2><p>Starting at age 25 (15 years to save, 8% returns): <strong>$3,613/month</strong> to reach $1.25M. At age 30 (10 years): $6,897/month. At 35 (5 years): $17,422/month. Starting 5 years earlier halves your required monthly savings. Use our <a href="https://www.qfinhub.com/calculators/compound-interest" target="_blank">compound interest calculator</a> to see your growth trajectory.</p><h2>FAQ</h2><p><strong>Q: Is retiring by 40 realistic?</strong><br>A: Yes, with 50-70% savings rate or very high income. Median FIRE achiever saves 60%+ for 10-15 years.</p><p><strong>Q: Healthcare before Medicare?</strong><br>A: Budget $400-$800/month for ACA plans. Add to expenses before calculating FIRE number.</p>`,\n  }',

    '  {\n  slug: "monthly-mortgage-payment-formula-tax-insurance",\n  title: "Monthly Mortgage Payment Formula With Tax and Insurance (PITI)",\n  description: "Learn the complete monthly mortgage payment formula including tax and insurance (PITI). Calculate principal, interest, property tax, and insurance in one formula.",\n  category: "mortgage",\n  publishedAt: new Date("2026-05-23"),\n  readingTime: 8,\n  relatedCalculators: ["mortgage-calculator", "amortization-schedule", "property-tax-calculator"],\n  content: `<h2>The Complete PITI Formula</h2><p>Your total monthly mortgage payment: <strong>PITI = M + (Annual Tax / 12) + (Annual Insurance / 12) + PMI</strong>. Where M = P [r(1+r)^n] / [(1+r)^n - 1]. Example: $300,000 loan at 6.5% for 30 years with $3,600 annual tax and $1,500 insurance. M = $1,896.20. Total PITI = $1,896.20 + $300 + $125 = <strong>$2,321.20</strong>. Use our <a href="https://www.qfinhub.com/calculators/mortgage-calculator" target="_blank">mortgage calculator</a> to compute instantly.</p><h2>Component Breakdown</h2><p><strong>Principal:</strong> Loan amount, paid down monthly. <strong>Interest:</strong> Cost of borrowing = remaining balance x monthly rate. <strong>Taxes:</strong> Property tax = 0.5-2.5% of home value annually, collected monthly in escrow. <strong>Insurance:</strong> $100-$150/month typical. <strong>PMI:</strong> Required if down payment under 20%, costs 0.5-1% of loan annually.</p><h2>Full Example: $300K Home</h2><p>20% down ($60K). Loan: $240K at 6.5%. M = $1,516.96. Tax ($300K x 1.2%): $300/month. Insurance: $125/month. Total PITI: $1,941.96. No PMI (20% down). Use our <a href="https://www.qfinhub.com/calculators/amortization-schedule" target="_blank">amortization calculator</a> for full schedule.</p><h2>FAQ</h2><p><strong>Q: Why (1+r)^n in the formula?</strong><br>A: Compound interest factor — (1+r)^n grows exponentially with loan term, explaining why longer loans cost much more.</p><p><strong>Q: Escrow required?</strong><br>A: Under 20% down: usually yes. Over 20%: often waivable. FHA/VA: always required.</p>`,\n  }',

    '  {\n  slug: "how-much-mortgage-afford-100k-salary",\n  title: "How Much Mortgage Can I Afford on $100K Salary? Exact Numbers",\n  description: "Earning $100K per year? Your max home price is $375K-$450K based on the 28/36 rule. Use our free calculator for your exact affordability with your debts and down payment.",\n  category: "mortgage",\n  publishedAt: new Date("2026-05-23"),\n  readingTime: 7,\n  relatedCalculators: ["mortgage-affordability", "mortgage-calculator", "debt-to-income"],\n  content: `<h2>You Can Afford $375K-$450K on $100K Salary</h2><p>With a $100,000 annual salary ($8,333/month gross), you can afford a home between <strong>$375,000 and $450,000</strong> depending on debt, down payment, and rate. The 28/36 rule: PITI must stay under 28% of gross income = $2,333/month. With 20% down and 6.5% rate, max mortgage is $300K-$360K = $375K-$450K home price. Use our <a href="https://www.qfinhub.com/calculators/mortgage-affordability" target="_blank">free affordability calculator</a> for your exact number.</p><h2>The 28/36 Rule</h2><p><strong>Front-end (28%):</strong> PITI / gross income under 28%. $100K: max $2,333/month. <strong>Back-end (36%):</strong> All debts / gross income under 36%. $100K: max $3,000/month. $500 in other debts = max PITI drops to $2,500. Use our <a href="https://www.qfinhub.com/calculators/debt-to-income" target="_blank">DTI calculator</a>.</p><h2>Down Payment Impact</h2><ul><li><strong>20% ($75K-$90K):</strong> Max $375K-$450K, no PMI</li><li><strong>10% ($37.5K-$45K):</strong> Max $333K-$400K, PMI ~$175/month</li><li><strong>5% ($18.75K-$22.5K):</strong> Max $295K-$355K, PMI ~$275/month</li></ul><p>PMI directly reduces buying power. Use our <a href="https://www.qfinhub.com/calculators/mortgage-calculator" target="_blank">mortgage calculator</a> to see scenarios.</p><h2>Sample: $400K Home on $100K</h2><p>20% down ($80K). Loan: $320K at 6.5%. P&I: $2,022. Tax: $400/mo. Insurance: $125/mo. Total: $2,547 — exceeds 28% guideline ($2,333). Solution: increase down payment to $115K or target $365K home. Use our <a href="https://www.qfinhub.com/calculators/mortgage-affordability" target="_blank">affordability calculator</a>.</p><h2>FAQ</h2><p><strong>Q: Stretch beyond 28%?</strong><br>A: Some lenders go to 43% DTI. But it leaves less for savings and emergencies. Experts recommend staying under 28%.</p><p><strong>Q: Student loans on $100K?</strong><br>A: $500/month student loan reduces max PITI from $2,333 to $2,000, dropping max home from $400K to ~$340K.</p>`,\n  }',
]

insertion = "\n" + ",\n".join(entries) + ",\n];"
new_content = content[:pos] + insertion

print(f"Slugs: {content.count('slug:')} -> {new_content.count('slug:')}")

if new_content.count('slug:') > content.count('slug:'):
    with open('/home/admin1/qfinhub/src/lib/blog/posts.ts', 'w') as f:
        f.write(new_content)
    print("DONE")
else:
    print("FAILED")
