import { type NextRequest, NextResponse } from "next/server";
import { createServerClient } from "@supabase/ssr";
import { readFileSync, existsSync } from "fs";
import { join } from "path";

const protectedPaths = ["/dashboard"];
const authPaths = ["/auth/login", "/auth/signup"];

// ─── 410 Gone for confirmed obsolete pages (Phase 12.13 + Jul 16 cleanup) ────
//
// Phase 12.13: Hand-picked GONE_PATHS set
// Jul 16 cleanup: Auto-load all known-obsolete /scenario/* and /calculators/refinance/*
// URLs from a build-time generated file (scripts/gone-urls.json). 410 is faster than 404
// for Google index removal.
//
// Live scenarios (NOT gone) all use the pattern `<topic>-<8-hex-hash>` like
// `retirement-planning-0a3c076a`. Anything under /scenario/ that does NOT match that
// pattern (e.g. `mortgage-1000k-10dp-10yr-8-5pct`, `401k-50000-10pct-30yr`) is a
// confirmed-obsolete formula scenario URL from Phase 35 cleanup.

const GONE_PATHS = new Set([
  // Phase 12.13 hand-picked
  "/scenario/401k-50000-10pct-30yr",
  "/calculators/refinance/las-vegas-nv",
  "/scenario/mortgage-250k-30dp-40yr-6-5pct",
  "/scenario/mortgage-350k-15dp-15yr-5-0pct",
  "/calculators/refinance/phoenix-az",
]);

// Auto-loaded from scripts/gone-urls.json (generated by scripts/build-gone-urls.ts
// or pre-baked from GSC extraction). Loaded lazily + cached.
let goneUrlsCache: Set<string> | null = null;

function loadGoneUrls(): Set<string> {
  if (goneUrlsCache) return goneUrlsCache;
  const goneUrlsPath = join(process.cwd(), "scripts", "gone-urls.json");
  if (!existsSync(goneUrlsPath)) {
    goneUrlsCache = new Set();
    return goneUrlsCache;
  }
  try {
    const data = JSON.parse(readFileSync(goneUrlsPath, "utf-8"));
    goneUrlsCache = new Set(data.paths || []);
  } catch {
    goneUrlsCache = new Set();
  }
  return goneUrlsCache;
}

// Live scenarios that should NOT be 410'd — these exist in /scenario/[id] dynamic route.
let liveScenariosCache: Set<string> | null = null;
const LIVE_SCENARIO_PATTERN = /^[a-z][a-z0-9-]*-[a-f0-9]{8}$/;

function isLiveScenario(slug: string): boolean {
  if (!LIVE_SCENARIO_PATTERN.test(slug)) return false;
  if (!liveScenariosCache) {
    const indexPath = join(process.cwd(), "public", "data", "scenarios", "index.json");
    if (!existsSync(indexPath)) {
      liveScenariosCache = new Set();
    } else {
      try {
        const data = JSON.parse(readFileSync(indexPath, "utf-8"));
        liveScenariosCache = new Set(Object.keys(data));
      } catch {
        liveScenariosCache = new Set();
      }
    }
  }
  return liveScenariosCache.has(slug);
}

export async function proxy(request: NextRequest) {
  const { pathname, searchParams } = request.nextUrl;

  // ── Aug 18, 2026: noindex,nofollow for any URL with ?lang= query param ──
  // The <HreflangTags /> component emits 8 alternate URLs per page (?lang=en|es|fr|
  // de|it|pt|hi|zh). Without this, Google indexes them and GSC reports them as
  // "Alternative page with proper canonical tag" (currently 59 pages in this bucket).
  // The X-Robots-Tag HTTP header is the canonical signal Google honors — no DOM
  // injection needed in middleware. They will deindex within 1-2 crawls.
  const lang = searchParams.get("lang");
  if (lang) {
    const response = NextResponse.next({
      request: { headers: new Headers(request.headers) },
    });
    response.headers.set("X-Robots-Tag", "noindex, nofollow");
    return response;
  }

  // ── 410 Gone for confirmed obsolete pages ────────────────────────
  // Phase 12.13 hardcoded paths
  if (GONE_PATHS.has(pathname)) {
    return new NextResponse("Gone", {
      status: 410,
      headers: { "Content-Type": "text/plain" },
    });
  }

  // /scenario/{slug} — return 410 unless slug matches a live hash-ID scenario
  if (pathname.startsWith("/scenario/")) {
    const slug = pathname.slice("/scenario/".length);
    if (slug && !isLiveScenario(slug)) {
      return new NextResponse("Gone", {
        status: 410,
        headers: { "Content-Type": "text/plain" },
      });
    }
  }

  // /calculators/refinance/{city} — all city variants are obsolete (Phase 12.13 cleanup)
  if (pathname.startsWith("/calculators/refinance/")) {
    return new NextResponse("Gone", {
      status: 410,
      headers: { "Content-Type": "text/plain" },
    });
  }

  // Auto-loaded gone-urls.json (generated from GSC extraction)
  const goneUrls = loadGoneUrls();
  if (goneUrls.has(pathname)) {
    return new NextResponse("Gone", {
      status: 410,
      headers: { "Content-Type": "text/plain" },
    });
  }

  let supabaseResponse = NextResponse.next({ request });

  const supabase = createServerClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    {
      cookies: {
        getAll() {
          return request.cookies.getAll();
        },
        setAll(cookiesToSet) {
          cookiesToSet.forEach(({ name, value }) =>
            request.cookies.set(name, value),
          );
          supabaseResponse = NextResponse.next({ request });
          cookiesToSet.forEach(({ name, value, options }) =>
            supabaseResponse.cookies.set(name, value, options),
          );
        },
      },
    },
  );

  const {
    data: { user },
  } = await supabase.auth.getUser();

  // ── Protect dashboard routes ────────────────────────────────
  // If not authenticated and trying to access /dashboard/*
  if (!user && protectedPaths.some((p) => pathname.startsWith(p))) {
    const url = request.nextUrl.clone();
    url.pathname = "/auth/login";
    url.search = `?redirectTo=${encodeURIComponent(pathname)}`;
    return NextResponse.redirect(url);
  }

  // ── Redirect logged-in users away from auth pages ─────────
  // If authenticated and on auth pages, send to dashboard
  if (user && authPaths.some((p) => pathname.startsWith(p))) {
    const url = request.nextUrl.clone();
    url.pathname = "/dashboard";
    return NextResponse.redirect(url);
  }

  return supabaseResponse;
}

export const config = {
  matcher: [
    /*
     * Aug 18, 2026: Catch-all matcher so the ?lang= noindex header is applied to
     * every page (not just the explicit scenario/refinance/dashboard/auth paths).
     * Without this, /blog?lang=fr, /decision?lang=en, /calculators/*?lang=hi etc.
     * would not pass through the proxy and Google would continue indexing them.
     *
     * Excludes:
     * - api/* (API routes, handle own headers)
     * - _next/static, _next/image (static files)
     * - favicon.ico
     * - public files (sitemaps, robots, etc.)
     */
    "/((?!api|_next/static|_next/image|favicon.ico|robots.txt|sitemap.xml|news-sitemap.xml|.*\\.).*)",
  ],
};