import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Disclaimer",
  description:
    "QFINHUB provides financial calculators for educational purposes only. Results are estimates and do not constitute financial, tax, or legal advice.",
  alternates: { canonical: "https://www.qfinhub.com/disclaimer" },
  robots: { index: true, follow: true },
};

export default function DisclaimerPage() {
  return (
    <main className="mx-auto max-w-3xl px-4 py-12 sm:px-6 lg:px-8">
      <h1 className="text-3xl font-bold tracking-tight text-gray-900 dark:text-white sm:text-4xl">
        Disclaimer
      </h1>
      <p className="mt-2 text-sm text-gray-500 dark:text-gray-400">
        Last updated: June 4, 2026
      </p>

      <div className="mt-8 space-y-6 text-gray-700 dark:text-gray-300">
        <section>
          <h2 className="text-xl font-semibold text-gray-900 dark:text-white">Educational Use Only</h2>
          <p className="mt-3 leading-relaxed">
            QFINHUB provides free financial calculators, guides, and comparison tools for <strong>educational and informational purposes only</strong>. All results, projections, and estimates generated by our calculators are based on the inputs you provide and standard mathematical formulas. They are not guaranteed to be accurate for your specific financial situation.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900 dark:text-white">Not Financial Advice</h2>
          <p className="mt-3 leading-relaxed">
            Nothing on QFINHUB constitutes <strong>financial advice, investment advice, tax advice, or legal advice</strong>. The calculators and content are tools for estimation and learning — they do not replace professional guidance. Always consult a qualified financial advisor, tax professional, or attorney before making significant financial decisions.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900 dark:text-white">Calculator Estimates</h2>
          <p className="mt-3 leading-relaxed">
            Our calculators use standardized formulas and default assumptions that <strong>may not reflect your actual circumstances</strong>. Interest rates, tax brackets, inflation, market returns, and other variables change over time. Results are estimates and should be used as a starting point for your own research — not as definitive financial projections.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900 dark:text-white">No Guarantees</h2>
          <p className="mt-3 leading-relaxed">
            QFINHUB makes no guarantees about the accuracy, completeness, or timeliness of any calculator, guide, or content on this site. We strive to keep our tools accurate and up to date, but financial calculations are complex and results may vary. Use at your own discretion.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900 dark:text-white">Third-Party Links</h2>
          <p className="mt-3 leading-relaxed">
            QFINHUB may link to third-party websites or resources. We do not endorse and are not responsible for the content, accuracy, or practices of any third-party site. Always review the terms and privacy policies of any external website you visit.
          </p>
        </section>
      </div>

      <div className="mt-12 rounded-xl border border-zinc-200 bg-gray-50 p-6 dark:border-zinc-700 dark:bg-zinc-900/50">
        <p className="text-sm text-gray-500 dark:text-gray-400">
          If you have questions about this disclaimer, please{" "}
          <Link href="/contact" className="text-primary-600 underline hover:text-primary-700">
            contact us
          </Link>
          .
        </p>
      </div>
    </main>
  );
}
