import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Disclaimer",
  description:
    "QFINHUB provides financial calculators for educational purposes only. Results are estimates and do not constitute financial, tax, or legal advice.",
  alternates: { canonical: "https://www.qfinhub.com/disclaimer" },
  robots: { index: true, follow: true },
};

export default function DisclaimerPage() {
  return (
    <main className="mx-auto max-w-3xl px-4 py-12 sm:px-6 lg:px-8">
      <h1 className="text-3xl font-bold tracking-tight text-gray-900 dark:text-white sm:text-4xl">
        Disclaimer
      </h1>
      <p className="mt-2 text-sm text-gray-500 dark:text-gray-400">
        Last updated: July 15, 2026
      </p>

      <div className="mt-8 space-y-6 text-gray-700 dark:text-gray-300">
        <section>
          <h2 className="text-xl font-semibold text-gray-900 dark:text-white">Educational Use Only</h2>
          <p className="mt-3 leading-relaxed">
            QFINHUB provides free financial calculators, guides, and comparison tools for{" "}
            <strong>educational and informational purposes only</strong>. All results, projections, and
            estimates generated by our calculators are based on the inputs you provide and standard
            mathematical formulas. They are not guaranteed to be accurate for your specific financial
            situation. The content on this site is general in nature and does not consider your
            personal objectives, financial situation, or needs. Before acting on any information
            from QFINHUB, you should consider its appropriateness to your circumstances and, where
            appropriate, seek professional advice from a licensed financial planner, accountant, or
            attorney in your jurisdiction.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900 dark:text-white">Not Financial Advice</h2>
          <p className="mt-3 leading-relaxed">
            Nothing on QFINHUB constitutes{" "}
            <strong>financial advice, investment advice, tax advice, or legal advice</strong>. The
            calculators and content are tools for estimation and learning. They do not replace
            professional guidance tailored to your individual circumstances. Any decision you make
            based on the output of our calculators is your own decision, and QFINHUB accepts no
            liability for outcomes arising from the use of our tools. Always consult a qualified
            Certified Financial Planner (CFP®), Certified Public Accountant (CPA), or licensed
            attorney before making significant financial decisions involving debt, investments, real
            estate, taxes, or retirement.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900 dark:text-white">Calculator Estimates and Limitations</h2>
          <p className="mt-3 leading-relaxed">
            Our calculators use standardized formulas and default assumptions that{" "}
            <strong>may not reflect your actual circumstances</strong>. Interest rates, tax brackets,
            inflation, market returns, and other variables change over time. Results are estimates
            and should be used as a starting point for your own research. Not as definitive financial
            projections. Specific limitations of our tools include:
          </p>
          <ul className="mt-3 list-disc space-y-2 pl-6">
            <li>
              Mortgage and loan calculators assume fixed rates and standard amortization unless you
              explicitly choose otherwise. Variable rates, balloon payments, prepayment penalties,
              and non-standard loan products are not modeled.
            </li>
            <li>
              Tax calculators use 2026 published federal and state brackets by default. Local taxes,
              credits, deductions, AMT, capital gains treatment, and self-employment adjustments are
              not included unless explicitly named.
            </li>
            <li>
              Investment and retirement calculators assume constant annual returns and ignore
              sequence-of-returns risk, market volatility, fees, taxes on withdrawals, and inflation
              unless those fields are explicitly filled in.
            </li>
            <li>
              Affordability calculators use the 28/36 rule-of-thumb as a heuristic. Actual lender
              decisions depend on credit score, debt-to-income ratio, employment history, and
              property-specific factors.
            </li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900 dark:text-white">No Guarantees</h2>
          <p className="mt-3 leading-relaxed">
            QFINHUB makes no guarantees about the accuracy, completeness, or timeliness of any
            calculator, guide, or content on this site. While we strive to keep our tools accurate
            and up to date, financial calculations are complex and results may vary due to rounding,
            input interpretation, edge-case scenarios, or formula updates. Past performance and
            projected returns are not indicators of future results. Use at your own discretion. If
            you find a calculation that appears incorrect, please use the{" "}
            <Link href="/contact" className="text-primary-600 underline hover:text-primary-700">
              contact form
            </Link>{" "}
            to report it. We investigate every error report and update affected calculators promptly.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900 dark:text-white">Third-Party Links and Advertisements</h2>
          <p className="mt-3 leading-relaxed">
            QFINHUB may link to third-party websites, government resources (such as IRS.gov,
            consumerfinance.gov, or sec.gov), or display advertising served by Google AdSense. We do
            not endorse and are not responsible for the content, accuracy, or practices of any
            third-party site. Advertisements are clearly labeled and do not represent endorsements
            of the advertised products or services. Sponsored or affiliate relationships, where they
            exist, are disclosed on the relevant page. Always review the terms and privacy policies
            of any external website you visit.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900 dark:text-white">Editorial Independence</h2>
          <p className="mt-3 leading-relaxed">
            All calculator methodology, editorial content, and recommendations on QFINHUB are
            developed independently by our editorial team. Advertisers and partners do not have
            advance review of, input into, or approval rights over our content. Our editorial
            standards are documented in our{" "}
            <Link href="/editorial-policy" className="text-primary-600 underline hover:text-primary-700">
              Editorial Policy
            </Link>
            . We do not accept payment in exchange for favorable reviews, rankings, or
            recommendations.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900 dark:text-white">Changes to This Disclaimer</h2>
          <p className="mt-3 leading-relaxed">
            We may update this Disclaimer from time to time to reflect changes in our practices,
            legal requirements, or the technologies we use. When we make material changes, we will
            update the "Last Updated" date at the top of this page. Your continued use of QFINHUB
            after any changes constitutes acceptance of the updated Disclaimer.
          </p>
        </section>
      </div>

      <div className="mt-12 rounded-xl border border-zinc-200 bg-gray-50 p-6 dark:border-zinc-700 dark:bg-zinc-900/50">
        <p className="text-sm text-gray-500 dark:text-gray-400">
          If you have questions about this disclaimer, please{" "}
          <Link href="/contact" className="text-primary-600 underline hover:text-primary-700">
            contact us
          </Link>
          .
        </p>
      </div>
    </main>
  );
}